[alembic]
script_location = alembic
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/villages_db

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemy]
level = WARNING

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
